print("BIRTHDAY LIST")
name_1 = input("\nHello, you are Friend #1! Input your name: ")
birthday_1 = input(f"\nHello, {name_1}! Now, input your birthday: ")
name_2 = input("\nHello, you are Friend #2! Input your name: ")
birthday_2 = input(f"\nHello, {name_2}! Now, input your birthday: ")
name_3 = input("\nHello, you are Friend #3! Input your name: ")
birthday_3 = input(f"\nHello, {name_3}! Now, input your birthday: ")
name_4 = input("\nHello, you are Friend #4! Input your name: ")
birthday_4 = input(f"\nHello, {name_4}! Now, input your birthday: ")
name_5 = input("\nHello, you are Friend #5! Input your name: ")
birthday_5 = input(f"\nHello, {name_5}! Now, input your birthday: ")
print(f"\n{name_1}: Was born on {birthday_1}")
print(f"\n{name_2}: Was born on {birthday_2}")
print(f"\n{name_3}: Was born on {birthday_3}")
print(f"\n{name_4}: Was born on {birthday_4}")
print(f"\n{name_5}: Was born on {birthday_5}")